defaults: &defaults
  name: ''

development:
  <<: *defaults
  port: 5000
  redis:
    url: 'redis://:@localhost:6379/'
  
test:
  <<: *defaults

production:
  <<: *defaults
  port: {{ env.PORT }}
  redis:
    url: {{ env.REDISTOGO_URL }}
