defaults: &defaults
  socketio:
    server: 'http://kittyballs.org'
  publishertoken: {{ env.PUBLISHERTOKEN }}
development:
  <<: *defaults
  socketio:
    server: {{ env.SOCKETIO_SERVER }}
  
test:
  <<: *defaults

production:
  <<: *defaults
